export const API_URL = 'https://api.unsplash.com'
export const API_URL_PHOTOS = `${API_URL}/photos`
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token'
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize'
export const ACCESS_KEY = 'CaHi_XF7bLUJJpzBS2gDXc4bgch-gjRT3azSYx2xfXk'
export const SECRET_KEY = 'qkYT5GOykHP2i-KJ9ngTkVQz_ks9pWmisFaKtB2XNXI'
export const REDIRECT_URI = 'https://shums89.github.io/gallery-methed'
export const RESPONSE_TYPE = 'code'
export const SCOPE = 'public read_user read_photos write_likes'